print('hello world \'my name\'')
print("hello world \"my name\"")
print("Hi i am hitendra \n okk\n mdmdm")
print("Hi i am gaurav \t hitendra")
print("Hi i am gaurav \\")
print("Hi i am gaurav \\\\")
print("Hi i am helllo\b")
print("Hi i am helllo\\n")
print('hi \\\\t')
print('hi \\\"\'')
print(" \\\" \\\' ")